name: mvs_reader
description: "PUB-читалка для працівника"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0
  flutter_html_all: ^3.0.0
  provider: ^6.1.5
  html: ^0.15.6
  characters: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  leak_tracker: ^10.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/1stChange.epub
    - assets/chapters.json
    - assets/DOVIDNIK_ORIGINAL.pdf
    - assets/2stChange.epub
    - assets/TEST.epub
    - assets/PROD.epub
    - assets/Оригінал/Original_Dovidnik_filtered.html
    - assets/Оригінал/Original_Dovidnik_filtered.fld/