name: mvs_reader
description: "PUB-читалка для працівника"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  epub_view: ^3.2.0
  epubx: ^4.0.0
  html: ^0.15.4
#  flutter_swipe_detector: ^2.0.0
  path_provider: ^2.1.5
  highlight_text: ^1.2.0
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/1stChange.epub
    - assets/chapters.json
    - assets/DOVIDNIK_ORIGINAL.pdf
    - assets/2stChange.epub
    - assets/TEST.epub
    - assets/PROD.epub
    - assets/TEST.html